name: build
on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules : true
      - uses: cachix/install-nix-action@v12
      - run: nix-shell --run "make release"
        env:
          NIX_PATH: nixpkgs=https://github.com/NixOS/nixpkgs/archive/20.09.tar.gz
